steps:
  - name: docker
    args:
      - build
      - --tag=gcr.io/salesforce-research-internal/${_IMAGE_NAME}:${_STAGE}
      - --file=./docker/Dockerfile.backend
      - .
images:
  - gcr.io/salesforce-research-internal/${_IMAGE_NAME}
