apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-agent
  namespace: sfr-ns-wenzhuo-yang
  labels:
    app: chat-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-agent
  template:
    metadata:
      labels:
        app: chat-agent
    spec:
      volumes:
        - name: sfr-home-pv-wenzhuo-yang
          persistentVolumeClaim:
            claimName: sfr-home-pvc-wenzhuo-yang
        - name: sfr-share-pv-wenzhuo-yang
          persistentVolumeClaim:
            claimName: sfr-share-pvc-wenzhuo-yang
      containers:
        - name: chat-agent
          image: "gcr.io/salesforce-research-internal/chatdemo-agent:v4"
          command: ["/opt/agent/run_celery.sh"]
          resources:
            limits:
              cpu: 8
              nvidia.com/gpu: 1
              memory: "32Gi"
          env:
            - name: REDIS_HOST
              value: redis-master
            - name: MODEL_CLASS
              value: "search"
            - name: MODEL_PATH
              value: "/export/share/wenzhuo/GPT-JT-6B-v1"
          volumeMounts:
            - name: sfr-home-pv-wenzhuo-yang
              mountPath: "/export/home"
            - name: sfr-share-pv-wenzhuo-yang
              mountPath: "/export/share"
      tolerations:
        - key: "gpu_num"
          operator: "Equal"
          value: "1"
          effect: "NoSchedule"
