apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-agent
  namespace: sfr-ns-wenzhuo-yang
  labels:
    app: chat-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-agent
  template:
    metadata:
      labels:
        app: chat-agent
    spec:
      volumes:
        - name: sfr-home-pv-wenzhuo-yang
          persistentVolumeClaim:
            claimName: sfr-home-pvc-wenzhuo-yang
        - name: sfr-share-pv-wenzhuo-yang
          persistentVolumeClaim:
            claimName: sfr-share-pvc-wenzhuo-yang
      containers:
        - name: chat-agent-triton
          image: "gcr.io/salesforce-research-internal/triton_with_ft:22.12"
          command: [ "/opt/tritonserver/bin/tritonserver" ]
          args: [ "--model-repository", "$(FT_MODEL_REPO)" ]
          resources:
            limits:
              cpu: 8
              nvidia.com/gpu: 1
              memory: "32Gi"
          env:
            - name: FT_MODEL_REPO
              value: "/export/share/wenzhuo/GPT-JT-6B-v1-1gpu"
          volumeMounts:
            - name: sfr-home-pv-wenzhuo-yang
              mountPath: "/export/home"
            - name: sfr-share-pv-wenzhuo-yang
              mountPath: "/export/share"
          livenessProbe:
            httpGet:
              path: /v2/health/ready
              port: 8000
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: 8000
            initialDelaySeconds: 120
        - name: chat-agent-celery
          image: "gcr.io/salesforce-research-internal/chatdemo-agent:v6"
          command: [ "/opt/agent/run_celery.sh" ]
          env:
            - name: REDIS_HOST
              value: redis-master
            - name: MODEL_CLASS
              value: "triton"
            - name: MODEL_PATH
              value: "/export/share/wenzhuo/GPT-JT-6B-v1"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      tolerations:
        - key: "gpu_num"
          operator: "Equal"
          value: "1"
          effect: "NoSchedule"
