apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-triton
  namespace: sfr-ns-wenzhuo-yang
  labels:
    app: chat-triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-triton
  template:
    metadata:
      labels:
        app: chat-triton
    spec:
      volumes:
        - name: sfr-home-pv-wenzhuo-yang
          persistentVolumeClaim:
            claimName: sfr-home-pvc-wenzhuo-yang
        - name: sfr-share-pv-wenzhuo-yang
          persistentVolumeClaim:
            claimName: sfr-share-pvc-wenzhuo-yang
      containers:
        - name: chat-triton
          image: "gcr.io/salesforce-research-internal/triton_with_ft:22.12"
          command: [ "/bin/bash" ]
          args: [ "-c", "/opt/tritonserver/bin/tritonserver --model-repository=$(FT_MODEL_REPO)" ]
          resources:
            limits:
              cpu: 8
              nvidia.com/gpu: 1
              memory: "32Gi"
          env:
            - name: FT_MODEL_REPO
              value: "/export/share/wenzhuo/GPT-JT-6B-v1-1gpu"
          volumeMounts:
            - name: sfr-home-pv-wenzhuo-yang
              mountPath: "/export/home"
            - name: sfr-share-pv-wenzhuo-yang
              mountPath: "/export/share"
          livenessProbe:
            httpGet:
              path: /v2/health/ready
              port: 8000
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: 8000
            initialDelaySeconds: 120
      tolerations:
        - key: "gpu_num"
          operator: "Equal"
          value: "1"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-triton
  namespace: sfr-ns-wenzhuo-yang
spec:
  type: ClusterIP
  selector:
    app: chat-triton
  ports:
    - name: chat-triton
      port: 8000
      targetPort: 8000
