FROM python:3.8-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gunicorn \
    && rm -rf /var/lib/apt/lists/*

COPY ./web/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /opt
RUN chmod +x /opt/web/run_web.sh

WORKDIR /opt
EXPOSE 8080
