FROM python:3.8-slim

COPY ./backend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /opt
RUN chmod +x /opt/backend/run_server.sh

WORKDIR /opt
EXPOSE 8081
