# FROM nvcr.io/nvidia/pytorch:22.08-py3
FROM python:3.8-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY ./agent/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /opt
RUN chmod +x /opt/agent/run_celery.sh

WORKDIR /opt
