apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfr-chat-a100
  namespace: sfr-ns-wenzhuo-yang
  labels:
    app: chat-a100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-a100
  template:
    metadata:
      labels:
        app: chat-a100
    spec:
      restartPolicy: Always
      volumes:
        - name: sfr-home-pv-wenzhuo-yang
          persistentVolumeClaim:
            claimName: sfr-home-pvc-wenzhuo-yang
        - name: sfr-share-pv-wenzhuo-yang
          persistentVolumeClaim:
            claimName: sfr-share-pvc-wenzhuo-yang
      containers:
        - name: chatdemo
          image: "gcr.io/salesforce-research-internal/chatdemo"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8081
              initialDelaySeconds: 1
          resources:
            limits:
              nvidia.com/gpu: 1
              cpu: "23"
              memory: 75G
          volumeMounts:
            - name: sfr-home-pv-wenzhuo-yang
              mountPath: "/export/home"
            - name: sfr-share-pv-wenzhuo-yang
              mountPath: "/export/share"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      tolerations:
        - key: "gpu_num"
          operator: "Equal"
          value: "1"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: sfr-chat-a100
spec:
  type: LoadBalancer
  selector:
    app: chat-a100
  ports:
    - name: chat-a100
      port: 8080
      targetPort: 8080
